coverage:
  status:
    project:
      default:
        # Current: ~70%. Platform-specific code (TPM, Linux power)
        # reduces achievable coverage in cross-platform CI.
        target: 70%
        threshold: 2%
    patch:
      default:
        # New code should maintain high coverage
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "tests/**/*"
  - "benches/**/*"
  - "examples/**/*"
  - "fuzz/**/*"
  - "src/bin/**/*"
